### ISSUE TITLE
Import FW sources for BDC BCB BAT boards

### ISSUE THREAD

**Issue by davidetome** [robotology/icub-firmware#121]
## Task description
Import/migrate the firmware sources for ``bdc`` and ``bcb`` boards from : 

- https://github.com/icub-tech-iit/electronics/tree/master/projects/boards/P2013_09_BDC/sw/BDC
- https://github.com/icub-tech-iit/electronics/tree/master/projects/boards/P2013_03_BCB/sw/BCB
- https://github.com/icub-tech-iit/electronics/tree/master/projects/boards/P2015_06_BAT/sw/BAT

## Definition of Done
the migraation is done

cc @marcoaccame

**Comment by davidetome** [comment]
see PR https://github.com/robotology/icub-firmware/pull/125

**Comment by MrAndrea** [comment]
Ciao @davidetome,
there are 2 firmware for the 2 revision of the BAT board, since they have different microcontroller.
For the first and obsolete revision, the firmware is in:
https://github.com/icub-tech-iit/electronics/tree/master/projects/boards/P2015_06_BAT/sw/BAT

For the latest board revision (iitcode 10050.C), the firmware is in:
https://github.com/icub-tech-iit/electronics/tree/master/projects/boards/P2015_06_BAT/sw/BAT%20Rev%20B

**Comment by davidetome** [comment]
@MrAndrea I moved also the `BAT Rev B` folder, please take a look at the [PR](https://github.com/icub-tech-iit/electronics/pull/45) and use `squash and merge`  instead `merge` as pointed out by @pattacini

**Comment by pattacini** [comment]
https://cloudfour.com/thinks/squashing-your-pull-requests/
