### ISSUE TITLE
calibration for torso CER

### ISSUE THREAD

**Issue by randaz81** [robotology/icub-firmware#25]
EMS boards controlling the torso tripod should respond to a specific calibration type message. Before receiving this message boards are not configured. Upon receiving the **three** required messages, joints start the calibration, moving towards the hardware limit  (the procedure is the same then icubv3 eyes, in that case two messages are required)

**Comment by ale-git** [comment]
The calibration procedure implemented is slightly different, because we have now different joints (with or without absolute encoders) with motor encoders that need calibration (iCub V3 motors, linear actuators, and so on), and calibrating a joint with absolute encoder or another one that relies only on motor encoder is transparent in the EMS with 2FOC controlled joints (it is the same thing from the high level point of view). In this way we can also avoid to add a new calibration type in the protocol, that is a quite long task. The procedure is thus the following: 
1) The joint responds to the usual type 3 (absolute encoder) calibration, and goes in calibration state.
2) When all absolute encoders in the group are calibrated, the motors in the group are turned on, and they start rotor encoder calibration.
3) The joints stay in calibration state until all motors signal that their encoders are calibrated. Motors that don't need calibration return "calibrated" state immediately (this is back compatible with iCub2 installed 2FOC firmware).
