### ISSUE TITLE
Error when opening boards associatd with strain

### ISSUE THREAD

**Issue by DanielePucci** [robotology/icub-firmware#36]
I am currently using the `iCubGenova02` (ETH robot). Then I open the `canLoader` with the `--calib` option, i.e.
~~~
 canLoader --calib
~~~

When I click on the `Calibrate` button after having connected to  a board associated with a strain,e.g. 

![screenshot from 2015-11-19 14 15 35](https://cloud.githubusercontent.com/assets/5045846/11271697/0a182c78-8ec8-11e5-80f5-ce8ce126ed48.png)

I get the following error on the terminal:

~~~
[ERROR]strain_get_matrix_rc : invalid response
[ERROR]strain_get_matrix_rc : invalid response
[ERROR]strain_get_matrix_rc : invalid response
[ERROR]strain_get_matrix_rc : invalid response
[ERROR]strain_get_matrix_rc : invalid response
[ERROR]strain_get_matrix_rc : invalid response
[ERROR]strain_get_matrix_rc : invalid response
[ERROR]strain_get_matrix_rc : invalid response
[ERROR]strain_get_matrix_rc : invalid response
[ERROR]strain_get_matrix_rc : invalid response
[ERROR]strain_get_matrix_rc : invalid response
[ERROR]strain_get_matrix_rc : invalid response
[ERROR]strain_get_matrix_rc : invalid response
[ERROR]strain_get_matrix_rc : invalid response
[ERROR]strain_get_matrix_rc : invalid response
[ERROR]strain_get_matrix_rc : invalid response
~~~

@valegagge @randaz81

**Comment by valegagge** [comment]
The problem was due to a wrong commit: on master branch there was implemented a new feature for use multiple calib matrices that needs a particular version of canLoader.

Moreover I noticed  bug fix about set_curr_tare message was missing.

Therefore I moved implementation of the new feature in a new branch called strain_with_ABCmatrix and restored bug fix on master. 

I released a new version of strain fw 3.0.4 in icub-firmware-build.

I tested it on my strain and all is ok.

@DanielePucci could you verify if the problem is solved? thank you

**Comment by DanielePucci** [comment]
Thank you very much @valegagge. I think that, however, we freeze the code on the iCubGenova02, and test this new feature as soon as the robot comes back (Monday 7th). Can't we test this improvement on the iCubGenova04?

**Comment by valegagge** [comment]
yes, of course!
I'll wait your feedback

**Comment by valegagge** [comment]
I updated strain sensors on iCubGenova04 with 3.0.4 version. All is ok.
