### ISSUE TITLE
2FOC and ETH board manage the CAN message for temperature limit configuration

### ISSUE THREAD

**Issue by valegagge** [robotology/icub-firmware#417]
Since we have to make the motor temperature limits configurable we need to:
- [x] define the new CAN messages (it could be similar to the SET_CURRENT_LIMIT)
- [x] implement the parser and former function in the ems
- [x] implement the parser function in 2foc and use it correctly. 
- [x] update the [CAN protocol documentation](https://github.com/robotology/icub-firmware/tree/master/emBODY/eBdocs/arch-arm)  

**Dod**
Implementation done on a branch.
This code needs an improvement in the icub-main to be tested

**Comment by MSECode** [comment]
DONE:

- CAN protocol updated with former method on ems for sending down to 2FOC the temperature limits data parsed from the configuration files (from mechanicals and motion control configuration files)

- CAN protocol updated with parser method on ems for parsing the data about the motor temperature elaborated from the 2FOC firmware and sent through a former method up to the ems. Check the modification to the parser method for handling frames coming from the 2FOC or from other boards

- CAN protocol updated on the 2FOC for defining the message and sending data about temperature to the ems board with a specific frequency as shown here (data are hard-coded for debugging reasons but the temperature is gotten through a specific method that points to the registry address on which we save the temperature value) 

Here the former of the 2FOC 

![image](https://github.com/robotology/icub-firmware/assets/77933235/68496ebb-63b9-41d4-8473-0c2583749320)

Here the parser on the ems 

![image](https://github.com/robotology/icub-firmware/assets/77933235/90e51a0a-ff54-487f-9b66-24af0d0208df)


TODO: 

- Finalise methods are clean debug comments.

- Check how data are parsed from the 2FOC 

- Regarding the previous point O realised that we do not need to send the parse the temperature related to motor1 from byte x and y and temperature related to motor2 from byte x+2 and y+2, since the 2FOC fw only sees one motor and therefore it will save the temperature for the specific motor x at bytes x and y only.
Then when we retrieve the data on the ems side, we need to get the specific motor entity based on the CAN address CAN1:1 or CAN1:2, considering that each 2FOC controls 2 motor ( the firmware of the 2 FOC that forms the 2FOC is the same running in parallel)

**Comment by MSECode** [comment]
Update --> The whole pipeline is currently working. It has been tested on the setup and and it is possible to get the motors temperatures by calling the specific IMotor API through and external yarp module.

- The message needed on the EMS board to set the temperature limits is the following: ICUBCANPROTO_POL_MC_CMD__SET_TEMPERATURE_LIMIT 

- And the correlated former is this: `extern eOresult_t eocanprotMCpolling_former_POL_MC_CMD__SET_TEMPERATURE_LIMIT(eOcanprot_descriptor_t *descriptor, eOcanframe_t *frame)`
which allows to create a CAN message containing the temperature limits to be sent to the 2FOC board to do the temperature management.

- Then, on the 2FOC board, the parser message `ICUBCANPROTO_POL_MC_CMD__SET_TEMPERATURE_LIMIT` has been added to the method `s_canIcubProtoParser_parse_pollingMsg`, so that the temperature peak limits can be handled by the 2foc baord.

- Finally, on the 2FOC board, the former message `ICUBCANPROTO_PER_MC_MSG__ADDITIONAL_STATUS` has been updated to add the temperature value to be sent towards the EMS and therefore the method `CanIcubProtoTrasmitterSendPeriodicData` has been updated with that CAN message

- Then, the related parser CAN message has been updated on the EMS side: `extern eOresult_t eocanprotMCperiodic_parser_PER_MC_MSG__ADDITIONAL_STATUS(eOcanframe_t *frame, eOcanport_t port)`

The firmware has been tested and commited

**Comment by valegagge** [comment]
Dod satified. Closing
