### ISSUE TITLE
Make the BAT compliant with the FW update

### ISSUE THREAD

**Issue by valegagge** [robotology/icub-firmware#445]
Recently we noticed that when the BAT is connected to the EMS, it is not possible to discover the 2foc boards connected to the same EMS board.

We already investigated on this issue and decided to fix it making the BAT silent when the FW updater is run. In other words, the BAT starts silently on the CAN channel, while continuing to update the screen.

The EMS will send the message `SET_TXMODE` of `analog polling class` with payload 0 when the BAT service starts by YRI. 
On reception on this message, the BAT starts to send its info on CAN as its usual rate(100 ms)

When the YRI is shutting down, and all devices are closing, the EMS will send the same message but with payload 1.
On its reception, the BAT stops to send data.

NOTE: please check `TSD-ICUBUNIT-canprotocol-sensorboards.docx` for more details about the CAN message

**Dod**
- [x] EMS and BAT update
- [x] FW PR done
- [x] tests done: the BAT starts silently and it sends CAN frames only when YRI is running.
- [x] The fw update of 2foc connected to the EMS with BAT board runs successfully

**Comment by MSECode** [comment]
Here the working branches of this feature:
- [icub-firmware](https://github.com/MSECode/icub-firmware/tree/feature/fwUpdaterBat)
- [icub-firmware-shared](https://github.com/MSECode/icub-firmware-shared/tree/fix/firmwareUdpater)

Basically we have done the following updates to EMS and BAT code:
- in the EMS, in the service `embot_app_eth_theBATservice` we have update the methods `can_battery_TX` and `can_battery_TXstop` in order to start and stop the CAN frame transmission of the BAT iff the ems has been started.
- in the BAT, we have filled the callback function triggered by the receiving of messages over CAN, checking that the CAN frame defining the start and stop of the transmission sent by the EMS is received and with which value. If 0 we start transmission, if 1 we stop it

In this manner we can start the BAT board as silent and we enable the transmission iff the YRI is up and running, so that we do not flood the CAN bus with messages while the ETH boards are in CAN GATEWAY MODE, while doing the Discovery in the FIrmwareUpdater

**Comment by valegagge** [comment]
Hi @MSECode ,
just a clarification: your setup is composed of:
- one EMS 
-  one BAT board connected to one CAN port of EMS
- 2 2FOC boards connected to the other CAN port of EMS.

Is this correct?

In this setup, that is equal to the situation on the robot, the firmware updater and yarprobotinterface work as expected, do they?

**Comment by MSECode** [comment]
So the setup, or to be precise the portion of the setup I've used, which is the only one connected via ethernet, is composed by the following boards:
- 1 EMS 
- 1 BAT 
- 1 FOC
- 1 MTB4
- 1 STRAIN

As you can see from the image below, the boards are the ones described

![MicrosoftTeams-image (1)](https://github.com/robotology/icub-firmware/assets/77933235/12f57aa3-9565-44dd-9567-17deede0074f)

Then, as highlighted by the FirmwareUpdater window, all boards are correctly found

![image](https://github.com/robotology/icub-firmware/assets/77933235/8a07494a-fbcc-4771-885d-435f0b9de9d5)

The tests I've done to check that our code is working as expected are the following:
- first, as shown above, I've just started the FirmwareUpdater and the CAN board discovery --> this is done to check that the BAT starts silent, therefore the CAN frames streaming is disabled
- then, I've tried to start the YRI and checked that the BAT is streaming --> this is done to check that the EMS correctly sends the transmission enabled command to the BAT, which reads it correctly, and starts the stream
- finally, I've stopped the YRI and re-discovered the CAN boards, to check that the BAT CAN frames streaming is now disabled --> this is done to check that EMS sends the STOP of the transmission when the YRI is going to be closed

All works as expected and the CAN boards are always found.

**Comment by valegagge** [comment]
Create pr for robots config with bat address 2.

cc @MSECode @valegagge

**Comment by valegagge** [comment]
> Create pr for robots config with bat address 2.
> 
> cc @MSECode @valegagge

We decided to address this sub-task in a new issue with the check of the empty CAN monitor configuration. 
While developing this feature, we noticed that the embObjBattery sends an empty CAN-monitor configuration. This creates an unexpected behavior: the CAN-monitor checks the presence of the battery boards with a period lower than the battery board transmission period.

Anyway, the Dod is satisfied.
