### ISSUE TITLE
Improve the CAN monitor configuration inside the `embot_app_eth_theBATservice`

### ISSUE THREAD

**Issue by valegagge** [robotology/icub-firmware#454]
This issue follows the #445 task. 

As explained here https://github.com/robotology/icub-firmware/issues/445#issuecomment-1870195848, we need to use a default configuration if the sent configuration is empty.

**Dod**

- [x] The above-mentioned check has been implemented
- [x] The entire feature is tested on the robot.
- [x] the PR of the robot's configuration is ready. In this PR the battery board needs the address `2` and the templates files are updated.(See here https://github.com/robotology/icub-firmware/issues/445#issuecomment-1870195848 for more details)

**Comment by MSECode** [comment]
Some of the improvements have been done. Specifically we have that:
- update the battery configuration files setting the CAN address to `2` and the PR is ready here: https://github.com/robotology/robots-configuration/pull/603
- in the firmware we have added the check on the `canmonitor` checkPeriod and if equal to zero, meaning not set, we are setting it to `250` so that it is lower than the max value, which is 254 being a uint8 datatype, and greater than the transmission rate of the bat which is 100 ms. Here the PR with the changes: https://github.com/robotology/icub-firmware/pull/447

**Comment by MSECode** [comment]
Tested current improvements pushed to the branches linked above on ergoCub robot and here the screen:
![MicrosoftTeams-image (2)](https://github.com/robotology/icub-firmware/assets/77933235/1128cf5b-5135-44b0-a565-0319c988d5fc)

**Comment by MSECode** [comment]
As you can see the BAT is sending correctly the messages when the YRI is started and no weird error is streamed on the YRI. (A couple of restarts have been done) and setting the check of the canmonitor at 250ms we have no error related to it continuosly printed on the YRI.

**Comment by MSECode** [comment]
CAN Frames and stop and start transmission message between frames

![image](https://github.com/robotology/icub-firmware/assets/77933235/62859f6c-2c5a-4056-81b7-55e9b305b350)

**Comment by MSECode** [comment]
All the PRs are here:
- [icub-firmware](https://github.com/robotology/icub-firmware/pull/447)
- [icub-firmware-shared](https://github.com/robotology/icub-firmware-shared/pull/91)
- [icub-firmware-build](https://github.com/robotology/icub-firmware-build/pull/126)

**Comment by MSECode** [comment]
cc: @valegagge

**Comment by valegagge** [comment]
it is also necessary the PR https://github.com/robotology/robots-configuration/pull/603

**Comment by MSECode** [comment]
PR closed --> moving to close state
